name: Testbatch Pale Ale
batch_size_l: 10.0
boil_time_min: 60
target_og_plato: 12.0
target_ibu: 20.0

mash_fermentables:
  - name: Pale Ale Malt
    percent: 70
  - name: Carapils
    percent: 23
  - name: Carafa2
    percent: 7
fermentor_fermentables:
  - name: Socker
    percent: 0
    extract_percent: 1.00
  - name: Honung
    percent: 0
    extract_percent: 0.95

boil_hops:
  - name: Magnum
    percent: 80
    boil_time_min: 75
  - name: Cascade
    percent: 15
    boil_time_min: 20
  - name: Cascade
    percent: 5
    boil_time_min: 5

dry_hops:
  - name: Citra
    amount_g_per_l: 4.0
    contact_time_days: 3
  - name: Mosaic
    amount_g_per_l: 2.5
    contact_time_days: 3