name: Black IPA
version: 1.1
batch_size_l: 10.0
boil_time_min: 120
target_og_plato: 12
target_ibu: 5.0

mash_fermentables:
  - name: Best a-xl
    percent: 40
  - name: Unmalted wheat
    percent: 60
fermentor_fermentables:

boil_hops:
  - name: Magnum
    percent: 100
    boil_time_min: 60

dry_hops:
